# Generated by Django 3.2.2 on 2021-08-18 02:18

import database.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210818_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to=database.models.notes_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
